import Link from 'next/link';
import React from 'react';

import { ROUTES } from '@/src/utils';

import { Typography } from '../../Typography/Typography';
import styles from '../banners.module.scss';

export const WelcomeBanner = () => (
  <div className={styles.orange_banner}>
    <Typography tag='h2' variant='title-1'>
      🚀 Here is simple app for data fetching (sorting, searching, filter)
    </Typography>
    <Typography tag='p' variant='sub-title-1'>
      Technology stack:
    </Typography>
    <Typography tag='span' variant='sub-title-2'>
      - Next 13
    </Typography>
    <Typography tag='span' variant='sub-title-2'>
      - React 18
    </Typography>
    <Typography tag='span' variant='sub-title-2'>
      - React-query
    </Typography>
    <Typography tag='span' variant='sub-title-2'>
      - GraphQl
    </Typography>
    <Typography tag='span' variant='sub-title-2'>
      - types generated by graphql-codegen
    </Typography>
    <Typography variant='title-2'>
      <Link href={ROUTES.SEARCH_ANIME} prefetch={false}>
        Click here to continue 🤖 {'>>>'}
      </Link>
    </Typography>
  </div>
);

export default WelcomeBanner;
