import React from 'react';

import { Typography } from '../../Typography/Typography';

import styles from '../banners.module.scss';
import Link from 'next/link';
import { ROUTES } from '@/src/utils';

export const WelcomeBanner = () => (
  <div className={styles.orange_banner}>
    <Typography variant='title-1' tag='h2'>
      🚀 Here is simple app for data fetching (sorting, searching, filter)
    </Typography>
    <Typography variant='sub-title-1' tag='p'>
      Technology stack:
    </Typography>
    <Typography tag='span' variant='sub-title-2'>
      - Next 13
    </Typography>
    <Typography tag='span' variant='sub-title-2'>
      - React 18
    </Typography>
    <Typography tag='span' variant='sub-title-2'>
      - React-query
    </Typography>
    <Typography tag='span' variant='sub-title-2'>
      - GraphQl
    </Typography>
    <Typography tag='span' variant='sub-title-2'>
      - types generated by graphql-codegen
    </Typography>
    <Typography variant='title-2'>
      <Link prefetch={false} href={ROUTES.SEARCH_ANIME}>
        Click here to continue 🤖 {'>>>'}
      </Link>
    </Typography>
  </div>
);

export default WelcomeBanner;
